# .YML FOR CONFIGURATION
# CONFIG FOR SPRING TO NEVER SHOW THE STACK TRACE ON CLIENT SIDE
server:
  error:
    include-stacktrace: never

## --------------------- DESCOMENTAR PARA RODAR OS TESTES --------------------------
#spring:
#  datasource:
#    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
#    driver-class-name: org.h2.Driver
#
#jpa:
#  hibernate:
#    hbm2ddl:
#      auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect

## CREATES CONNECTION WITH THE DATABASE
## ------------------------- HABILITAR PARA RODAR O PROJETO ------------------------------
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/anime?useSSL=false&createDatabaseIfNotExists=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    # UPDATES THE DATABASE EVERYTIME THE APPLICATION CREATES SOMETHING NEW
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      hibernate:
        SQL:
          debug