# .YML FOR CONFIGURATION
# CONFIG FOR SPRING TO NEVER SHOW THE STACK TRACE ON CLIENT SIDE
server:
  error:
    include-stacktrace: never

# CREATES CONNECTION WITH THE DATABASE
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/anime?useSSL=false&createDatabaseIfNotExists=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    # UPDATES THE DATABASE EVERYTIME THE APPLICATION CREATES SOMETHING NEW
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      hibernate:
        SQL:
          debug